### ISSUE TITLE
Can't install integration

### ISSUE THREAD

**Issue by ehn** [JohNan/home-assistant-covid-19-swe#1]
I have added this custom component's repository to HACS and installed it. Going to Configuration, Integrations, Add integration and searching for "COVID-19 Sweden" shows nothing. Am I missing something?

**Comment by JohNan** [comment]
That's strange. Did you restart Home Assistant after installing the integration?

**Comment by ehn** [comment]
I did restart. However, this morning, it works without changing anything. I assume it was a frontend caching issue.
